echo '\e[0;31m      .                       '
echo '      |`.                     '
echo '      ;  `.                   '
echo '      ; :. \           __     '
echo '      ; ; \ \      .--"  \    '
echo '      ; ;  ; ;     :      \   '
echo '      ; ;  : :     ; ;     ;  '
echo '      '"'"' :   ; ;    ;::     :  '
echo '       \ \  : ;--.-;; l     ; '
echo '        \ \  ;:    :;//'"'"'-.__: '
echo '        /\ \ ::____:::-\      '
echo '       /  ).:+'"'"'""""""""=\     '
echo '      :_,=""     /"-.    ;    '
echo '      ;"       .'"'"'    `.  |    '
echo '     :      .-^=    ==.\ |    '
echo '     |  _.-".gp      gp:;:    '
echo '     ;    /  $$      $$;: ;   '
echo '    :    :  `--      --:  |   '
echo '    ;    ;\        ,   '"'"'  |   '
echo '   :    :  \      _   /   :   '
echo '   ;    |   `.   `-'"'"' /     ;  '
echo '  :     :    :`-.__.'"'"'      |  '
echo '  ;          ;     :       |  '
echo ' :     ...._/      '"'"'.__..  |  '
echo ' ;   .'"'"'                  \ ;  '
echo ':   /                   _ Y   '
echo ';  :         .g$$p.    d$$+.  '
echo ';  ;     :.g$$$$$$$$p.d$$$$$b '
echo ':  :     :$$$$$$$$$$$T$$$$$$$;'
echo ' \  ;    ;$$$$S$$$$$$$S$$$$$P '
echo '  `.|    |$$$$S$$$$$$$S$$$$P  '
echo '    |    |T$$$$$SSSSS$$$$$$   '
echo '    :    | `T$$$$$$$$$$$$$;   '
echo '     ;   |   $$$$$$$$$$$$$    '
echo '     |   :   $$$$$$$$$$$$;    '
echo '     :    ; d$$$$$$$$$$$$;    '
echo '     |    :d$$$$$$$$$$$$$$    '
echo '     ;    :"^T$$$$$$$$$$$$b   '
echo '    :     ;   `T$$$$$$$$$$P;  '
echo '    ;    :      `T$$$$$$$P :  '
echo '    |    ;        T$$$$$P   ; '
echo '    |   :          T$$P'"'"'    ; '
echo '    :   ;           $'"'"'      : '
echo '   ._;__;           :       : '
echo '   ; ;  ;           |       : '
echo '   :_L__:           |       ; '
echo '   .'"'"'    ;          |       ; '
echo ' .'"'"'      :          |      :  '
echo ':/ _.-.  :;         |      |  '
echo '/.'"'"'    \ |:         |      ;  '
echo '/  bug  ;| ;        |     :   '
echo '        `'"'"' :        |     |   '
echo '            ;       |     ;   '
echo '            :       |    :    '
echo '             ;      |    |    '
echo '             :      :    ;    '
echo '             :    _.'"'"'-   ;    '
echo '             ;     /:    :    '
echo '            /     / ;     ;   '
echo '           /     :  ;     :   '
echo '          :      ;  ;     :   '
echo '          ;     :  :      :   '
echo '         :      ;  :      ;   '
echo '         ;     :   ;     :    '
echo '        :      ;   ;     ;    '
echo '        ;     :    ;    :     '
echo '        ;     ;    ;    ;     '
echo '        ;    :     ;   :      '
echo '        |    ;     ;   ;      '
echo '        |   :      ;  :       '
echo '        |   ;      ;  ;       '
echo '        :  :       :  ;       '
echo '        ;  :       :  :       '
echo '       :    ,      ;   ;      '
echo '       ;    ;      ;   :      '
echo '      :     :      :    ;     '
echo '      :     ;      :b__d$     '
echo '      $b   d$       $$$$$     '
echo '      :$bgd$;        T$P'"'"'     '
echo '       T$$$P                  '
echo '        '"'"'"'"'"''
